### ISSUE TITLE
'Conflict' error when creating new account

### ISSUE THREAD

**Issue by DebugBios** [L-Leite/cso2-webapp#4]
![1](https://user-images.githubusercontent.com/44349391/65434197-5d488480-de59-11e9-9799-88cb4b774fe7.PNG)
Login is also experiencing errors.

But in-game logins work as normal.

**Comment by Ochii** [comment]
Which user name are you using to create the account?

**Comment by DebugBios** [comment]
The error was reported in the discode and he seems to have duplicated his ID. 

I personally join and log in will become normal.
