### ISSUE TITLE
How to create new pages?

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-webapp#6]
index.pug
user.pug

 + download.pug or training.pug how do I add from which file?

**Comment by felixabi** [comment]
I want to add more pages

**Comment by L-Leite** [comment]
Page templates are placed under [src/views](https://github.com/L-Leite/cso2-webapp/tree/master/src/views). You can create a new page there

**Comment by felixabi** [comment]
page does not see download.pug

**Comment by L-Leite** [comment]
Are you asking for a download page?

**Comment by felixabi** [comment]
for example:
/home page
/account - user
/download page
/cso2 about
/Player-ranking
/news
/media
/support - only mail info page



If you do .php for webapp this will make it easier to make design.
and it will be great if it automatically sees the inserted pages

**Comment by L-Leite** [comment]
I don't plan on migrating the web app to PHP, but you can create one yourself since all the data it's using comes from other services

**Comment by felixabi** [comment]
fixed
